from PySide6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QLabel, 
                               QListWidget, QListWidgetItem, QStackedWidget, QFrame, 
                               QScrollArea, QGridLayout, QSizePolicy)
from PySide6.QtCore import Qt

class GlossaryItem(QWidget):
    def __init__(self, title, description, setup_callback):
        super().__init__()
        layout = QVBoxLayout(self)
        layout.setContentsMargins(24, 32, 24, 32)
        
        # Title and Description
        t_lbl = QLabel(title)
        t_lbl.setStyleSheet("font-size: 28px; font-weight: bold; color: #0f172a;")
        d_lbl = QLabel(description)
        d_lbl.setStyleSheet("font-size: 15px; color: #475569; margin-bottom: 24px; line-height: 1.5;")
        d_lbl.setWordWrap(True)
        
        layout.addWidget(t_lbl)
        layout.addWidget(d_lbl)
        
        # Phone Simulator Container
        sim_container = QWidget()
        sim_layout = QHBoxLayout(sim_container)
        sim_layout.setAlignment(Qt.AlignCenter)
        
        self.phone = QFrame()
        self.phone.setFixedSize(320, 640)
        self.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
        
        self.p_layout = QVBoxLayout(self.phone)
        self.p_layout.setContentsMargins(0, 0, 0, 0)
        self.p_layout.setSpacing(0)
        
        sim_layout.addWidget(self.phone)
        layout.addWidget(sim_container)
        layout.addStretch()
        
    def add_widget_to_phone(self, widget, stretch=0, alignment=None):
        if alignment is not None:
            self.p_layout.addWidget(widget, stretch, alignment)
        else:
            self.p_layout.addWidget(widget, stretch)

class MobileGlossaryTool(QWidget):
    def __init__(self):
        super().__init__()
        self.items = []
        self._setup_ui()
        
    def _setup_ui(self):
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        
        self.menu = QListWidget()
        self.menu.setFixedWidth(280)
        self.menu.setStyleSheet("""
            QListWidget {
                background-color: #ffffff;
                border-right: 1px solid #e2e8f0;
                outline: none;
                padding-top: 12px;
            }
            QListWidget::item {
                padding: 12px 20px;
                color: #475569;
                font-size: 14px;
                border-bottom: 1px solid transparent;
            }
            QListWidget::item:selected {
                background-color: #eff6ff;
                color: #2563eb;
                font-weight: bold;
                border-left: 4px solid #2563eb;
            }
            QListWidget::item:hover:!selected {
                background-color: #f8fafc;
                color: #0f172a;
            }
        """)
        self.menu.currentRowChanged.connect(self._on_menu_changed)
        
        self.stack = QStackedWidget()
        self.stack.setStyleSheet("background-color: #ffffff;")
        
        layout.addWidget(self.menu)
        layout.addWidget(self.stack)
        
        # Build phases
        self._build_phase_1()
        self._build_phase_2()
        self._build_phase_3()
        self._build_phase_4()
        self._build_phase_5()
        self._build_phase_6()
        
        if self.menu.count() > 0:
            self.menu.setCurrentRow(0)
            
    def _add_item(self, title, desc, setup_fn):
        item = GlossaryItem(title, desc, setup_fn)
        setup_fn(item)
        self.items.append(item)
        
        list_item = QListWidgetItem(title)
        self.menu.addItem(list_item)
        self.stack.addWidget(item)
        
    def _on_menu_changed(self, index):
        if 0 <= index < self.stack.count():
            self.stack.setCurrentIndex(index)

    # ------------------ PHASE 1 ------------------
    def _build_phase_1(self):
        def setup_splash(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            logo = QFrame()
            logo.setFixedSize(80, 80)
            logo.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #3b82f6, stop:1 #1d4ed8); border-radius: 24px;")
            ll = QVBoxLayout(logo)
            ll.setAlignment(Qt.AlignCenter)
            txt = QLabel("V")
            txt.setStyleSheet("color: white; font-size: 40px; font-weight: bold; background: transparent;")
            ll.addWidget(txt)
            title = QLabel("VibeApp")
            title.setStyleSheet("color: #0f172a; font-size: 24px; font-weight: bold; margin-top: 20px; background: transparent;")
            title.setAlignment(Qt.AlignCenter)
            l.addWidget(logo, alignment=Qt.AlignCenter)
            l.addWidget(title)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Splash Screen", "Layar pembuka dengan logo aplikasi.", setup_splash)

        def setup_onboarding(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            img = QFrame()
            img.setFixedSize(200, 200)
            img.setStyleSheet("background-color: #f1f5f9; border-radius: 100px; border: 2px dashed #cbd5e1;")
            title = QLabel("Welcome to Vibe")
            title.setAlignment(Qt.AlignCenter)
            title.setStyleSheet("color: #0f172a; font-size: 20px; font-weight: bold; margin-top: 24px; background: transparent;")
            desc = QLabel("Discover the best UI design patterns.")
            desc.setAlignment(Qt.AlignCenter)
            desc.setStyleSheet("color: #64748b; font-size: 14px; background: transparent;")
            dots = QWidget()
            dl = QHBoxLayout(dots)
            dl.setAlignment(Qt.AlignCenter)
            for i in range(3):
                d = QFrame()
                d.setFixedSize(8 if i!=0 else 24, 8)
                d.setStyleSheet(f"background-color: {'#3b82f6' if i==0 else '#e2e8f0'}; border-radius: 4px;")
                dl.addWidget(d)
            l.addWidget(img, alignment=Qt.AlignCenter)
            l.addWidget(title)
            l.addWidget(desc)
            l.addSpacing(20)
            l.addWidget(dots)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Onboarding / Walkthrough", "Tutorial singkat atau pengenalan fitur saat aplikasi pertama kali diinstal.", setup_onboarding)

        def setup_hero(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setContentsMargins(0,0,0,0)
            l.setAlignment(Qt.AlignTop)
            hero = QFrame()
            hero.setFixedHeight(240)
            hero.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #10b981, stop:1 #047857); border-top-left-radius: 26px; border-top-right-radius: 26px;")
            hl = QVBoxLayout(hero)
            hl.setAlignment(Qt.AlignCenter)
            ht = QLabel("Explore Nature")
            ht.setStyleSheet("color: white; font-size: 28px; font-weight: bold; background: transparent;")
            hs = QLabel("Find your next adventure")
            hs.setStyleSheet("color: #d1fae5; font-size: 14px; background: transparent;")
            hl.addWidget(ht, alignment=Qt.AlignCenter)
            hl.addWidget(hs, alignment=Qt.AlignCenter)
            l.addWidget(hero)
            l.addStretch()
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Hero (Hero Image)", "Banner visual besar di bagian atas layar untuk menarik perhatian pengguna.", setup_hero)

        def setup_bottomnav(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setContentsMargins(0,0,0,0)
            l.setAlignment(Qt.AlignBottom)
            nav = QFrame()
            nav.setFixedHeight(80)
            nav.setStyleSheet("background-color: white; border-top: 1px solid #e2e8f0; border-bottom-left-radius: 26px; border-bottom-right-radius: 26px;")
            nl = QHBoxLayout(nav)
            nl.setContentsMargins(20, 10, 20, 20)
            nl.setAlignment(Qt.AlignJustify)
            for icon, label, active in [("🏠", "Home", True), ("🔍", "Search", False), ("👤", "Profile", False)]:
                btn = QWidget()
                bl = QVBoxLayout(btn)
                bl.setContentsMargins(0,0,0,0)
                bl.setSpacing(4)
                bl.setAlignment(Qt.AlignCenter)
                ic = QLabel(icon)
                ic.setStyleSheet(f"font-size: 20px; color: {'#3b82f6' if active else '#94a3b8'}; background: transparent;")
                ic.setAlignment(Qt.AlignCenter)
                lb = QLabel(label)
                lb.setStyleSheet(f"font-size: 10px; font-weight: {'bold' if active else 'normal'}; color: {'#3b82f6' if active else '#94a3b8'}; background: transparent;")
                lb.setAlignment(Qt.AlignCenter)
                bl.addWidget(ic)
                bl.addWidget(lb)
                nl.addWidget(btn)
            l.addWidget(nav)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Bottom Navigation (Tab Bar)", "Menu navigasi utama di bagian bawah layar.", setup_bottomnav)

        def setup_hamburger(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QHBoxLayout(c)
            l.setContentsMargins(0,0,0,0)
            drawer = QFrame()
            drawer.setFixedWidth(200)
            drawer.setStyleSheet("background-color: white; border-top-left-radius: 26px; border-bottom-left-radius: 26px; border-right: 1px solid #e2e8f0;")
            dl = QVBoxLayout(drawer)
            dl.setAlignment(Qt.AlignTop)
            dl.setContentsMargins(20,40,20,20)
            header = QLabel("Menu")
            header.setStyleSheet("font-size: 20px; font-weight: bold; color: #0f172a; margin-bottom: 20px; background: transparent;")
            dl.addWidget(header)
            for m in ["Dashboard", "Settings", "Help", "Logout"]:
                mi = QLabel(m)
                mi.setStyleSheet("font-size: 16px; color: #475569; padding: 12px 0px; border-bottom: 1px solid #f1f5f9; background: transparent;")
                dl.addWidget(mi)
            content = QWidget()
            content.setStyleSheet("background-color: rgba(15, 23, 42, 0.1); border-top-right-radius: 26px; border-bottom-right-radius: 26px;")
            l.addWidget(drawer)
            l.addWidget(content, 1)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Hamburger Menu (Drawer)", "Menu navigasi samping yang muncul saat ikon garis tiga ditekan.", setup_hamburger)

        def setup_appbar(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setContentsMargins(0,0,0,0)
            l.setAlignment(Qt.AlignTop)
            header = QFrame()
            header.setFixedHeight(60)
            header.setStyleSheet("background-color: white; border-bottom: 1px solid #e2e8f0; border-top-left-radius: 26px; border-top-right-radius: 26px;")
            hl = QHBoxLayout(header)
            hl.setContentsMargins(16,0,16,0)
            back = QLabel("←")
            back.setStyleSheet("font-size: 20px; color: #0f172a; background: transparent;")
            title = QLabel("Settings")
            title.setStyleSheet("font-size: 18px; font-weight: bold; color: #0f172a; background: transparent;")
            title.setAlignment(Qt.AlignCenter)
            search = QLabel("🔍")
            search.setStyleSheet("font-size: 16px; color: #0f172a; background: transparent;")
            hl.addWidget(back)
            hl.addWidget(title, 1)
            hl.addWidget(search)
            l.addWidget(header)
            l.addStretch()
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Top App Bar (Header)", "Area atas berisi judul, navigasi kembali, atau aksi utama halaman.", setup_appbar)

        def setup_segmented(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignTop)
            l.setContentsMargins(0, 20, 0, 0)
            seg = QFrame()
            seg.setFixedHeight(40)
            seg.setFixedWidth(240)
            seg.setStyleSheet("background-color: #f1f5f9; border-radius: 8px; padding: 4px;")
            sl = QHBoxLayout(seg)
            sl.setContentsMargins(4,4,4,4)
            sl.setSpacing(0)
            t1 = QLabel("Chats")
            t1.setAlignment(Qt.AlignCenter)
            t1.setStyleSheet("background-color: white; border-radius: 6px; font-weight: bold; color: #0f172a; border: 1px solid #e2e8f0;")
            t2 = QLabel("Calls")
            t2.setAlignment(Qt.AlignCenter)
            t2.setStyleSheet("background-color: transparent; color: #64748b;")
            sl.addWidget(t1, 1)
            sl.addWidget(t2, 1)
            l.addWidget(seg, alignment=Qt.AlignHCenter)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Segmented Control (Tabs)", "Tombol tab datar (biasanya berisi 2-3 opsi) untuk berpindah tampilan di layar yang sama.", setup_segmented)

        def setup_breadcrumbs(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignTop)
            l.setContentsMargins(20,40,20,20)
            bc = QLabel("Home  <span style='color:#cbd5e1;'>&gt;</span>  Electronics  <span style='color:#cbd5e1;'>&gt;</span>  <b>Laptops</b>")
            bc.setStyleSheet("font-size: 14px; color: #64748b; background: transparent;")
            l.addWidget(bc)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Breadcrumbs", "Jalur navigasi teks yang menunjukkan posisi halaman saat ini.", setup_breadcrumbs)

        def setup_safe(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setContentsMargins(0,0,0,0)
            top_danger = QFrame()
            top_danger.setFixedHeight(48)
            top_danger.setStyleSheet("background-color: rgba(244, 63, 94, 0.1); border-top-left-radius: 26px; border-top-right-radius: 26px;")
            tdl = QVBoxLayout(top_danger)
            notch = QFrame()
            notch.setFixedSize(120, 24)
            notch.setStyleSheet("background-color: #0f172a; border-bottom-left-radius: 12px; border-bottom-right-radius: 12px; border-top-left-radius: 0; border-top-right-radius: 0;")
            tdl.addWidget(notch, alignment=Qt.AlignTop | Qt.AlignHCenter)
            tdl.setContentsMargins(0,0,0,0)
            safe = QFrame()
            safe.setStyleSheet("background-color: rgba(16, 185, 129, 0.05); border: 2px dashed rgba(16, 185, 129, 0.5);")
            sl = QVBoxLayout(safe)
            lbl = QLabel("Safe Area\n(Aman untuk konten)")
            lbl.setAlignment(Qt.AlignCenter)
            lbl.setStyleSheet("color: #047857; font-weight: bold; background: transparent;")
            sl.addWidget(lbl)
            bot_danger = QFrame()
            bot_danger.setFixedHeight(34)
            bot_danger.setStyleSheet("background-color: rgba(244, 63, 94, 0.1); border-bottom-left-radius: 26px; border-bottom-right-radius: 26px;")
            l.addWidget(top_danger)
            l.addWidget(safe, 1)
            l.addWidget(bot_danger)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Safe Area", "Area yang dijamin tidak tertutup oleh lekukan layar (notch), kamera, atau bilah sistem.", setup_safe)

    # ------------------ PHASE 2 ------------------
    def _build_phase_2(self):
        def setup_cta(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setContentsMargins(0,0,0,0)
            l.setAlignment(Qt.AlignBottom)
            bot = QFrame()
            bot.setFixedHeight(90)
            bot.setStyleSheet("background-color: #ffffff; border-top: 1px solid #e2e8f0; border-bottom-left-radius: 26px; border-bottom-right-radius: 26px;")
            bl = QVBoxLayout(bot)
            bl.setContentsMargins(24, 16, 24, 24)
            btn = QLabel("Buy Now")
            btn.setAlignment(Qt.AlignCenter)
            btn.setStyleSheet("background-color: #2563eb; color: white; font-weight: bold; font-size: 16px; border-radius: 12px;")
            bl.addWidget(btn)
            l.addWidget(bot)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("CTA (Call to Action)", "Tombol utama yang dirancang menonjol agar pengguna melakukan tindakan penting.", setup_cta)

        def setup_fab(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setContentsMargins(0,0,24,24)
            l.setAlignment(Qt.AlignBottom | Qt.AlignRight)
            fab = QLabel("+")
            fab.setAlignment(Qt.AlignCenter)
            fab.setFixedSize(56, 56)
            fab.setStyleSheet("background-color: #2563eb; color: white; font-size: 32px; border-radius: 28px;")
            l.addWidget(fab)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("FAB (Floating Action Button)", "Tombol melayang berbentuk bulat, biasanya di pojok kanan bawah.", setup_fab)

        def setup_modal(item):
            c = QWidget()
            c.setStyleSheet("background-color: rgba(15, 23, 42, 0.5); border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            l.setContentsMargins(32, 0, 32, 0)
            modal = QFrame()
            modal.setStyleSheet("background-color: #ffffff; border-radius: 16px;")
            ml = QVBoxLayout(modal)
            ml.setContentsMargins(24, 24, 24, 24)
            title = QLabel("Delete Item?")
            title.setStyleSheet("font-size: 18px; font-weight: bold; color: #0f172a; background: transparent;")
            desc = QLabel("Are you sure you want to delete this item? This action cannot be undone.")
            desc.setWordWrap(True)
            desc.setStyleSheet("font-size: 14px; color: #475569; margin-top: 8px; background: transparent;")
            acts = QWidget()
            acts.setStyleSheet("background: transparent;")
            al = QHBoxLayout(acts)
            al.setAlignment(Qt.AlignRight)
            al.setContentsMargins(0,0,0,0)
            b1 = QLabel("Cancel")
            b1.setStyleSheet("color: #64748b; font-weight: bold;")
            b2 = QLabel("Delete")
            b2.setStyleSheet("color: #f43f5e; font-weight: bold; margin-left: 16px;")
            al.addWidget(b1)
            al.addWidget(b2)
            ml.addWidget(title)
            ml.addWidget(desc)
            ml.addSpacing(16)
            ml.addWidget(acts)
            l.addWidget(modal)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Modal / Dialog", "Jendela pop-up yang muncul di tengah layar.", setup_modal)

        def setup_bottomsheet(item):
            c = QWidget()
            c.setStyleSheet("background-color: rgba(15, 23, 42, 0.5); border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setContentsMargins(0,0,0,0)
            l.setAlignment(Qt.AlignBottom)
            sheet = QFrame()
            sheet.setFixedHeight(220)
            sheet.setStyleSheet("background-color: #ffffff; border-top-left-radius: 24px; border-top-right-radius: 24px; border-bottom-left-radius: 26px; border-bottom-right-radius: 26px;")
            sl = QVBoxLayout(sheet)
            sl.setAlignment(Qt.AlignTop)
            handle = QFrame()
            handle.setFixedSize(40, 4)
            handle.setStyleSheet("background-color: #cbd5e1; border-radius: 2px;")
            sl.addWidget(handle, alignment=Qt.AlignCenter)
            sl.addSpacing(16)
            for t in ["Share", "Copy Link", "Report"]:
                lbl = QLabel(t)
                lbl.setStyleSheet("font-size: 16px; color: #0f172a; padding: 12px 20px; background: transparent;")
                sl.addWidget(lbl)
            l.addWidget(sheet)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Bottom Sheet", "Panel menu yang muncul menyelinap dari bawah layar.", setup_bottomsheet)

        def setup_snackbar(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setContentsMargins(16, 0, 16, 24)
            l.setAlignment(Qt.AlignBottom)
            snack = QFrame()
            snack.setFixedHeight(48)
            snack.setStyleSheet("background-color: #0f172a; border-radius: 8px;")
            sl = QHBoxLayout(snack)
            sl.setContentsMargins(16, 0, 16, 0)
            txt = QLabel("Item saved to favorites")
            txt.setStyleSheet("color: #f8fafc; font-size: 14px; background: transparent;")
            act = QLabel("UNDO")
            act.setStyleSheet("color: #38bdf8; font-weight: bold; background: transparent;")
            sl.addWidget(txt, 1)
            sl.addWidget(act)
            l.addWidget(snack)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Snackbar / Toast", "Pesan singkat yang muncul sementara di bagian bawah layar.", setup_snackbar)

        def setup_tooltip(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            tt = QFrame()
            tt.setStyleSheet("background-color: #0f172a; border-radius: 6px;")
            ttl = QVBoxLayout(tt)
            ttl.setContentsMargins(12, 8, 12, 8)
            txt = QLabel("Hold to record")
            txt.setStyleSheet("color: #ffffff; font-size: 12px; background: transparent;")
            ttl.addWidget(txt)
            icon = QLabel("🎤")
            icon.setStyleSheet("font-size: 28px; background: transparent; margin-top: 8px;")
            l.addWidget(tt, alignment=Qt.AlignCenter)
            l.addWidget(icon, alignment=Qt.AlignCenter)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Tooltip", "Balon teks petunjuk singkat.", setup_tooltip)

    # ------------------ PHASE 3 ------------------
    def _build_phase_3(self):
        def setup_card(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            l.setContentsMargins(24, 0, 24, 0)
            card = QFrame()
            card.setStyleSheet("background-color: #ffffff; border-radius: 16px; border: 1px solid #e2e8f0;")
            cl = QVBoxLayout(card)
            cl.setContentsMargins(0,0,0,0)
            img = QFrame()
            img.setFixedHeight(140)
            img.setStyleSheet("background-color: #38bdf8; border-top-left-radius: 16px; border-top-right-radius: 16px;")
            info = QWidget()
            info.setStyleSheet("background: transparent;")
            il = QVBoxLayout(info)
            il.setContentsMargins(16, 16, 16, 16)
            t = QLabel("Mount Bromo")
            t.setStyleSheet("font-size: 18px; font-weight: bold; color: #0f172a;")
            d = QLabel("Active volcano in East Java")
            d.setStyleSheet("font-size: 14px; color: #64748b; margin-top: 4px;")
            il.addWidget(t)
            il.addWidget(d)
            cl.addWidget(img)
            cl.addWidget(info)
            l.addWidget(card)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Card", "Wadah berbentuk kotak berbatas untuk mengelompokkan informasi.", setup_card)

        def setup_carousel(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            l.setContentsMargins(0,0,0,0)
            sa = QScrollArea()
            sa.setWidgetResizable(True)
            sa.setStyleSheet("border: none; background: transparent;")
            sc = QWidget()
            sc.setStyleSheet("background: transparent;")
            sl = QHBoxLayout(sc)
            sl.setContentsMargins(20, 0, 20, 0)
            for col in ["#f43f5e", "#10b981", "#3b82f6"]:
                bx = QFrame()
                bx.setFixedSize(200, 280)
                bx.setStyleSheet(f"background-color: {col}; border-radius: 16px;")
                sl.addWidget(bx)
            sa.setWidget(sc)
            l.addWidget(sa)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Carousel / Slider", "Kumpulan gambar atau kartu yang bisa digeser (swipe) ke kiri-kanan.", setup_carousel)

        def setup_listview(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignTop)
            l.setContentsMargins(0, 24, 0, 0)
            for i in range(4):
                row = QWidget()
                row.setStyleSheet("background: transparent;")
                rl = QHBoxLayout(row)
                rl.setContentsMargins(20, 12, 20, 12)
                av = QFrame()
                av.setFixedSize(48, 48)
                av.setStyleSheet("background-color: #e2e8f0; border-radius: 24px;")
                txt = QLabel(f"User Name {i+1}")
                txt.setStyleSheet("font-size: 16px; font-weight: bold; color: #0f172a;")
                rl.addWidget(av)
                rl.addSpacing(12)
                rl.addWidget(txt, 1)
                l.addWidget(row)
                if i < 3:
                    div = QFrame()
                    div.setFixedHeight(1)
                    div.setStyleSheet("background-color: #f1f5f9; margin-left: 80px;")
                    l.addWidget(div)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("List View", "Daftar konten yang tersusun vertikal ke bawah.", setup_listview)

        def setup_gridview(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QGridLayout(c)
            l.setContentsMargins(20, 20, 20, 20)
            l.setSpacing(16)
            for i in range(4):
                bx = QFrame()
                bx.setFixedSize(110, 110)
                bx.setStyleSheet("background-color: #f1f5f9; border-radius: 12px;")
                l.addWidget(bx, i//2, i%2)
            l.setRowStretch(2, 1)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Grid View", "Tampilan daftar yang disusun dalam bentuk matriks.", setup_gridview)
        
        def setup_skeleton(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignTop)
            l.setContentsMargins(20, 40, 20, 0)
            for _ in range(2):
                row = QWidget()
                row.setStyleSheet("background: transparent;")
                rl = QHBoxLayout(row)
                rl.setContentsMargins(0, 0, 0, 24)
                av = QFrame()
                av.setFixedSize(48, 48)
                av.setStyleSheet("background-color: #e2e8f0; border-radius: 24px;")
                texts = QWidget()
                tl = QVBoxLayout(texts)
                tl.setContentsMargins(12, 0, 0, 0)
                t1 = QFrame()
                t1.setFixedSize(120, 12)
                t1.setStyleSheet("background-color: #e2e8f0; border-radius: 6px;")
                t2 = QFrame()
                t2.setFixedSize(80, 12)
                t2.setStyleSheet("background-color: #f1f5f9; border-radius: 6px;")
                tl.addWidget(t1)
                tl.addWidget(t2)
                rl.addWidget(av)
                rl.addWidget(texts, 1)
                l.addWidget(row)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Skeleton Loading", "Animasi blok abu-abu pengganti loading spinner.", setup_skeleton)
        
        def setup_badge(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            av_c = QWidget()
            av_c.setFixedSize(60, 60)
            av_c.setStyleSheet("background: transparent;")
            av = QFrame(av_c)
            av.setFixedSize(48, 48)
            av.setStyleSheet("background-color: #e2e8f0; border-radius: 24px;")
            av.move(0, 12)
            badge = QLabel("3", av_c)
            badge.setAlignment(Qt.AlignCenter)
            badge.setFixedSize(24, 24)
            badge.setStyleSheet("background-color: #ef4444; color: white; border-radius: 12px; font-weight: bold; font-size: 12px; border: 2px solid white;")
            badge.move(36, 0)
            l.addWidget(av_c, alignment=Qt.AlignCenter)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Badge", "Titik notifikasi angka kecil berwarna.", setup_badge)

    # ------------------ PHASE 4 ------------------
    def _build_phase_4(self):
        def setup_textfield(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            l.setContentsMargins(24, 0, 24, 0)
            lbl = QLabel("Email Address")
            lbl.setStyleSheet("font-size: 14px; font-weight: bold; color: #0f172a; margin-bottom: 8px;")
            tf = QFrame()
            tf.setFixedHeight(52)
            tf.setStyleSheet("background-color: #f8fafc; border: 1px solid #cbd5e1; border-radius: 12px;")
            tfl = QHBoxLayout(tf)
            tfl.setContentsMargins(16, 0, 16, 0)
            ph = QLabel("john.doe@example.com")
            ph.setStyleSheet("color: #94a3b8; font-size: 14px; background: transparent;")
            tfl.addWidget(ph)
            l.addWidget(lbl)
            l.addWidget(tf)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Text Field & Placeholder", "Kotak input tempat pengguna mengetikkan teks.", setup_textfield)

        def setup_toggle(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            row = QWidget()
            rl = QHBoxLayout(row)
            lbl = QLabel("Dark Mode")
            lbl.setStyleSheet("font-size: 16px; font-weight: bold; color: #0f172a; background: transparent;")
            t_bg = QFrame()
            t_bg.setFixedSize(52, 28)
            t_bg.setStyleSheet("background-color: #2563eb; border-radius: 14px;")
            dot = QFrame(t_bg)
            dot.setFixedSize(24, 24)
            dot.setStyleSheet("background-color: white; border-radius: 12px;")
            dot.move(26, 2)
            rl.addWidget(lbl)
            rl.addStretch()
            rl.addWidget(t_bg)
            l.addWidget(row)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Toggle / Switch", "Tombol geser on/off.", setup_toggle)
        
        def setup_checkbox(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            row = QWidget()
            rl = QHBoxLayout(row)
            cb = QFrame()
            cb.setFixedSize(24, 24)
            cb.setStyleSheet("background-color: #2563eb; border-radius: 6px;")
            chk = QLabel("✓", cb)
            chk.setStyleSheet("color: white; font-weight: bold; font-size: 14px; background: transparent;")
            chk.move(6, 2)
            lbl = QLabel("Remember me")
            lbl.setStyleSheet("color: #0f172a; font-size: 16px; background: transparent;")
            rl.addWidget(cb)
            rl.addSpacing(12)
            rl.addWidget(lbl)
            rl.addStretch()
            l.addWidget(row)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Checkbox", "Kotak centang untuk memilih satu atau beberapa opsi.", setup_checkbox)

        def setup_radio(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            row = QWidget()
            rl = QHBoxLayout(row)
            rb = QFrame()
            rb.setFixedSize(24, 24)
            rb.setStyleSheet("background-color: white; border: 6px solid #2563eb; border-radius: 12px;")
            lbl = QLabel("Option 1")
            lbl.setStyleSheet("color: #0f172a; font-size: 16px; background: transparent;")
            rl.addWidget(rb)
            rl.addSpacing(12)
            rl.addWidget(lbl)
            rl.addStretch()
            l.addWidget(row)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Radio Button", "Pilihan ganda dengan tombol bulat.", setup_radio)

        def setup_chips(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QHBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            for txt, active in [("Design", True), ("Code", False)]:
                chip = QLabel(txt)
                if active:
                    chip.setStyleSheet("background-color: #2563eb; color: white; padding: 10px 20px; border-radius: 20px; font-weight: bold; font-size: 14px;")
                else:
                    chip.setStyleSheet("background-color: #f1f5f9; color: #475569; padding: 10px 20px; border-radius: 20px; font-size: 14px;")
                l.addWidget(chip)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Chips / Tags", "Komponen kecil lonjong yang mewakili atribut atau filter.", setup_chips)
        
        def setup_slider(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            track = QFrame()
            track.setFixedHeight(8)
            track.setStyleSheet("background-color: #e2e8f0; border-radius: 4px;")
            fill = QFrame(track)
            fill.setFixedSize(140, 8)
            fill.setStyleSheet("background-color: #2563eb; border-radius: 4px;")
            thumb = QFrame(track)
            thumb.setFixedSize(24, 24)
            thumb.setStyleSheet("background-color: white; border-radius: 12px; border: 2px solid #2563eb;")
            thumb.move(130, -8)
            l.addWidget(track)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Slider", "Garis dengan tombol yang bisa digeser mengatur rentang nilai.", setup_slider)

    # ------------------ PHASE 5 ------------------
    def _build_phase_5(self):
        def setup_pull(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignTop)
            spin_c = QWidget()
            sl = QVBoxLayout(spin_c)
            sl.setAlignment(Qt.AlignCenter)
            sl.setContentsMargins(0, 30, 0, 20)
            spin = QFrame()
            spin.setFixedSize(40, 40)
            spin.setStyleSheet("background-color: white; border-radius: 20px; border: 3px solid #cbd5e1; border-top-color: #2563eb;")
            sl.addWidget(spin)
            row = QFrame()
            row.setFixedHeight(120)
            row.setStyleSheet("background-color: white; border-radius: 16px; margin: 0 20px; border: 1px solid #e2e8f0;")
            l.addWidget(spin_c)
            l.addWidget(row)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Pull to Refresh", "Gestur menarik layar ke bawah.", setup_pull)
        
        def setup_progress(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            track = QFrame()
            track.setFixedHeight(8)
            track.setStyleSheet("background-color: #e2e8f0; border-radius: 4px;")
            fill = QFrame(track)
            fill.setFixedSize(140, 8)
            fill.setStyleSheet("background-color: #10b981; border-radius: 4px;")
            l.addWidget(track)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Progress Bar / Spinner", "Indikator loading.", setup_progress)
        
        def setup_swipe(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            row = QFrame()
            row.setFixedSize(240, 70)
            row.setStyleSheet("background-color: #ef4444; border-radius: 12px;")
            del_lbl = QLabel("Delete", row)
            del_lbl.setStyleSheet("color: white; font-weight: bold; background: transparent;")
            del_lbl.move(180, 25)
            fore = QFrame(row)
            fore.setFixedSize(190, 70)
            fore.setStyleSheet("background-color: #f8fafc; border-radius: 12px; border: 1px solid #e2e8f0;")
            lbl = QLabel("Swipe to delete", fore)
            lbl.setStyleSheet("color: #0f172a; font-weight: bold; font-size: 14px;")
            lbl.move(20, 25)
            l.addWidget(row, alignment=Qt.AlignCenter)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Swipe Action", "Gestur menggeser item.", setup_swipe)
        
        def setup_accordion(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignTop)
            l.setContentsMargins(20, 40, 20, 0)
            acc = QFrame()
            acc.setStyleSheet("background-color: #f8fafc; border-radius: 12px; border: 1px solid #e2e8f0;")
            al = QVBoxLayout(acc)
            h = QWidget()
            hl = QHBoxLayout(h)
            title = QLabel("What is Vibe?")
            title.setStyleSheet("font-weight: bold; color: #0f172a;")
            arr = QLabel("▼")
            arr.setStyleSheet("color: #64748b; font-size: 10px;")
            hl.addWidget(title)
            hl.addStretch()
            hl.addWidget(arr)
            b = QLabel("Vibe is a UI design pattern library.")
            b.setStyleSheet("color: #475569; padding-left: 10px; padding-bottom: 10px;")
            al.addWidget(h)
            al.addWidget(b)
            l.addWidget(acc)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Accordion / Expandable", "Daftar menu yang bisa diperluas.", setup_accordion)
        
        def setup_stepper(item):
            c = QWidget()
            c.setStyleSheet("background-color: #ffffff; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            step = QWidget()
            sl = QHBoxLayout(step)
            sl.setAlignment(Qt.AlignCenter)
            c1 = QFrame()
            c1.setFixedSize(30, 30)
            c1.setStyleSheet("background-color: #10b981; border-radius: 15px;")
            n1 = QLabel("✓", c1)
            n1.setStyleSheet("color: white; font-weight: bold; background: transparent;")
            n1.move(9, 7)
            l1 = QFrame()
            l1.setFixedSize(40, 2)
            l1.setStyleSheet("background-color: #10b981;")
            c2 = QFrame()
            c2.setFixedSize(30, 30)
            c2.setStyleSheet("background-color: #2563eb; border-radius: 15px;")
            n2 = QLabel("2", c2)
            n2.setStyleSheet("color: white; font-weight: bold; background: transparent;")
            n2.move(10, 7)
            l2 = QFrame()
            l2.setFixedSize(40, 2)
            l2.setStyleSheet("background-color: #e2e8f0;")
            c3 = QFrame()
            c3.setFixedSize(30, 30)
            c3.setStyleSheet("background-color: #e2e8f0; border-radius: 15px;")
            n3 = QLabel("3", c3)
            n3.setStyleSheet("color: #94a3b8; font-weight: bold; background: transparent;")
            n3.move(10, 7)
            sl.addWidget(c1)
            sl.addWidget(l1)
            sl.addWidget(c2)
            sl.addWidget(l2)
            sl.addWidget(c3)
            l.addWidget(step)
            item.phone.setStyleSheet("background-color: #ffffff; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Stepper", "Indikator tahapan langkah.", setup_stepper)

    # ------------------ PHASE 6 ------------------
    def _build_phase_6(self):
        def setup_empty(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            icon = QLabel("📦")
            icon.setStyleSheet("font-size: 60px; background: transparent;")
            title = QLabel("No Data Found")
            title.setStyleSheet("font-size: 20px; font-weight: bold; color: #0f172a; margin-top: 16px; background: transparent;")
            desc = QLabel("There's nothing here yet.")
            desc.setStyleSheet("color: #64748b; background: transparent;")
            l.addWidget(icon, alignment=Qt.AlignCenter)
            l.addWidget(title, alignment=Qt.AlignCenter)
            l.addWidget(desc, alignment=Qt.AlignCenter)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Empty State", "Layar ketika belum ada data.", setup_empty)
        
        def setup_404(item):
            c = QWidget()
            c.setStyleSheet("background-color: #f8fafc; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            title = QLabel("404")
            title.setStyleSheet("font-size: 80px; font-weight: bold; color: #2563eb; background: transparent;")
            desc = QLabel("Page Not Found")
            desc.setStyleSheet("font-size: 18px; color: #475569; background: transparent;")
            btn = QLabel("Go Back")
            btn.setStyleSheet("background-color: #0f172a; color: white; padding: 12px 24px; border-radius: 12px; margin-top: 24px;")
            l.addWidget(title, alignment=Qt.AlignCenter)
            l.addWidget(desc, alignment=Qt.AlignCenter)
            l.addWidget(btn, alignment=Qt.AlignCenter)
            item.phone.setStyleSheet("background-color: #f8fafc; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Error State (404)", "Tampilan saat terjadi kesalahan.", setup_404)
        
        def setup_onboardingscreen(item):
            c = QWidget()
            c.setStyleSheet("background-color: #2563eb; border-radius: 26px;")
            l = QVBoxLayout(c)
            l.setAlignment(Qt.AlignCenter)
            title = QLabel("Ready to Start?")
            title.setStyleSheet("font-size: 24px; font-weight: bold; color: white; background: transparent;")
            btn = QLabel("Get Started")
            btn.setStyleSheet("background-color: white; color: #2563eb; font-weight: bold; padding: 14px 40px; border-radius: 20px; font-size: 16px; margin-top: 30px;")
            l.addWidget(title, alignment=Qt.AlignCenter)
            l.addWidget(btn, alignment=Qt.AlignCenter)
            item.phone.setStyleSheet("background-color: #2563eb; border: 14px solid #0f172a; border-radius: 40px;")
            item.add_widget_to_phone(c, 1)
        self._add_item("Success State", "Layar konfirmasi keberhasilan.", setup_onboardingscreen)
